idf_component_register(
    SRCS
        "src/setting.c"
        "src/controller/controller.c"
        "src/service/service.c"
        "src/view/view.c"
        "src/view/wifi_view.c"
        "assets/generated/setting_icon.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        common
        app_manager
        data_center
        wifi_manager
        lvgl
        waveshare__esp32_c6_touch_amoled_2_06
)
