#pragma once

#include "lvgl.h"

#define APP_COMMON_BACKGROUND_COLOR 0xFAFAFA
#define APP_COMMON_PANEL_COLOR 0x132637
#define APP_COMMON_PANEL_BORDER_COLOR 0x24445C
#define APP_COMMON_TEXT_COLOR 0x0C0C0C
#define APP_COMMON_MUTED_TEXT_COLOR 0x93A8B8
#define APP_COMMON_ACCENT_COLOR 0x33D6A6

#define APP_COMMON_TITLE_FONT (&lv_font_montserrat_32)
#define APP_COMMON_BODY_FONT (&lv_font_montserrat_24)

#define APP_COMMON_TITLE_PAD_TOP 60
#define APP_COMMON_TITLE_PAD_BOTTOM 12
#define APP_COMMON_TITLE_PAD_LEFT 16
#define APP_COMMON_TITLE_PAD_RIGHT 16
#define APP_COMMON_TITLE_CONTENT_GAP 24

#define APP_COMMON_CONTAINER_PAD_ROW 18
#define APP_COMMON_CONTAINER_PAD_COLUMN 18